# Generated by Django 5.0 on 2024-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_invoice_alter_gamecenterdevice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecenterdevice',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
