# Generated by Django 5.0 on 2024-05-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_time_remove_gamecenterdevice_end_time_calctime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='refreshments',
        ),
        migrations.CreateModel(
            name='Refresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.gamecenterdevice')),
                ('refreshs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.refreshment')),
            ],
        ),
        migrations.AddField(
            model_name='gamecenterdevice',
            name='refreshments',
            field=models.ManyToManyField(related_name='refreshs_owned', through='devices.Refresh', to='devices.refreshment'),
        ),
    ]
