# Generated by Django 5.0 on 2024-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_remove_refreshment_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calctime',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='calctime',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calctime',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
