# Generated by Django 5.0 on 2024-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_calctime_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calctime',
            name='diff',
        ),
        migrations.AlterField(
            model_name='calctime',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calctime',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
