# Generated by Django 5.0 on 2024-05-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_remove_calctime_diff_alter_calctime_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='start_time',
        ),
    ]
