# Generated by Django 5.0 on 2024-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_remove_gamecenterdevice_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecenterdevice',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
