# Generated by Django 5.0 on 2024-05-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_gamecenterdevice_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refresh',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.gamecenterdevice'),
        ),
        migrations.AlterField(
            model_name='refresh',
            name='refreshs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.refreshment'),
        ),
    ]
