# Generated by Django 5.0 on 2024-05-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_alter_calctime_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calctime',
            name='time_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.time'),
        ),
    ]
