# Generated by Django 5.0 on 2024-05-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_calctime_time_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calctime',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.gamecenterdevice'),
        ),
    ]
