# Generated by Django 5.0 on 2024-05-28 11:43

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_calctime_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='refreshments',
        ),
        migrations.RemoveField(
            model_name='refresh',
            name='device',
        ),
        migrations.AddField(
            model_name='invoice',
            name='refreshment',
            field=models.ManyToManyField(related_name='refreshs_owned', through='devices.Refresh', to='devices.refreshment'),
        ),
        migrations.AddField(
            model_name='refresh',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamecenterdevice',
            name='person_name',
            field=models.CharField(default='لا احد', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='device'),
        ),
        migrations.CreateModel(
            name='InvoiceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.gamecenterdevice')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='device',
            field=models.ManyToManyField(related_name='device_owned', through='devices.InvoiceDevice', to='devices.gamecenterdevice'),
        ),
        migrations.AlterField(
            model_name='gamecenterdevice',
            name='invoice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.invoicetype'),
        ),
    ]
