# Generated by Django 5.0 on 2024-05-28 11:49

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_invoicetype_remove_gamecenterdevice_refreshments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='device'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicedevice',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.invoice'),
        ),
    ]
