# Generated by Django 5.0 on 2024-05-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_invoice_slug_alter_invoice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='slug',
        ),
    ]
