# Generated by Django 5.0 on 2024-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_alter_calctime_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecenterdevice',
            name='invoice_type',
            field=models.CharField(choices=[('محدد', 'محدد'), ('مفتوح', 'مفتوح'), ('دين', 'دين')], default='None', max_length=100),
        ),
        migrations.DeleteModel(
            name='InvoiceType',
        ),
    ]
