# Generated by Django 5.0 on 2024-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_gamecenterdevice_invoice_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='person_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('محدد', 'محدد'), ('مفتوح', 'مفتوح'), ('دين', 'دين')], default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='person_name',
            field=models.CharField(default='لا احد', max_length=200, null=True),
        ),
    ]
