# Generated by Django 5.0 on 2024-06-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_remove_gamecenterdevice_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecenterdevice',
            name='type',
            field=models.CharField(choices=[('فردي', 'فردي'), ('زوجي', 'زوجي')], max_length=6, null=True),
        ),
    ]
