# Generated by Django 5.0 on 2024-06-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_gamecenterdevice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='gamecenterdevice',
            name='type',
        ),
        migrations.AlterField(
            model_name='calctime',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calctime',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
