# Generated by Django 5.0 on 2024-06-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_remove_gamecenterdevice_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calctime',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
