# Generated by Django 5.0 on 2024-06-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_alter_calctime_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshment',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
