# Generated by Django 5.0 on 2024-06-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_refreshment_img_delete_device_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshment',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
