# Generated by Django 5.0 on 2024-06-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_alter_refreshment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshment',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
