# Generated by Django 5.0 on 2024-06-13 21:44

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_alter_refreshment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshment',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to=''),
        ),
    ]
