# Generated by Django 5.0 on 2024-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_alter_refreshment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('واصل', 'واصل'), ('دين', 'دين')], default='None', max_length=100, null=True),
        ),
    ]
